export const data = [
  {
    iso: "AE",
    country: "United Arab Emirates",
    year: 2018,
    gdpPerCap: 41327,
    population: 9.63,
    lifeExpectancy: 77.81,
    researchDevExpenditure: 1.3,
    scientificTechnicalJournalArticles: 3145,
    patentApplications: 56,
    region: "Asia",
    subRegion: "Western Asia",
  },
  {
    iso: "AF",
    country: "Afghanistan",
    year: 2018,
    gdpPerCap: 565,
    population: 37.17,
    lifeExpectancy: 64.49,
    scientificTechnicalJournalArticles: 112,
    region: "Asia",
    subRegion: "Southern Asia",
  },
  {
    iso: "AG",
    country: "Antigua and Barbuda",
    year: 2018,
    gdpPerCap: 15135,
    population: 0.1,
    lifeExpectancy: 76.89,
    scientificTechnicalJournalArticles: 6,
    patentApplications: 5,
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
  },
  {
    iso: "AL",
    country: "Albania",
    year: 2018,
    gdpPerCap: 5075,
    population: 2.87,
    lifeExpectancy: 78.46,
    scientificTechnicalJournalArticles: 180,
    patentApplications: 15,
    region: "Europe",
    subRegion: "Southern Europe",
  },
  {
    iso: "AM",
    country: "Armenia",
    year: 2018,
    gdpPerCap: 4407,
    population: 2.95,
    lifeExpectancy: 74.94,
    researchDevExpenditure: 0.19,
    scientificTechnicalJournalArticles: 521,
    patentApplications: 101,
    region: "Asia",
    subRegion: "Western Asia",
  },
  {
    iso: "AO",
    country: "Angola",
    year: 2018,
    gdpPerCap: 3234,
    population: 30.81,
    lifeExpectancy: 60.78,
    scientificTechnicalJournalArticles: 30,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
  {
    iso: "AR",
    country: "Argentina",
    year: 2018,
    gdpPerCap: 10050,
    population: 44.49,
    lifeExpectancy: 76.52,
    scientificTechnicalJournalArticles: 8811,
    patentApplications: 425,
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
  },
  {
    iso: "AT",
    country: "Austria",
    year: 2018,
    gdpPerCap: 50052,
    population: 8.84,
    lifeExpectancy: 81.69,
    researchDevExpenditure: 3.17,
    scientificTechnicalJournalArticles: 12362,
    patentApplications: 2039,
    region: "Europe",
    subRegion: "Western Europe",
  },
  {
    iso: "AU",
    country: "Australia",
    year: 2018,
    gdpPerCap: 56832,
    population: 24.98,
    lifeExpectancy: 82.75,
    scientificTechnicalJournalArticles: 53610,
    patentApplications: 2757,
    region: "Oceania",
    subRegion: "Australia and New Zealand",
  },
  {
    iso: "AZ",
    country: "Azerbaijan",
    year: 2018,
    gdpPerCap: 5801,
    population: 9.94,
    lifeExpectancy: 72.86,
    researchDevExpenditure: 0.18,
    scientificTechnicalJournalArticles: 761,
    patentApplications: 155,
    region: "Asia",
    subRegion: "Western Asia",
  },
  {
    iso: "BA",
    country: "Bosnia and Herzegovina",
    year: 2018,
    gdpPerCap: 6097,
    population: 3.32,
    lifeExpectancy: 77.26,
    researchDevExpenditure: 0.2,
    scientificTechnicalJournalArticles: 704,
    patentApplications: 84,
    region: "Europe",
    subRegion: "Southern Europe",
  },
  {
    iso: "BB",
    country: "Barbados",
    year: 2018,
    gdpPerCap: 16137,
    population: 0.29,
    lifeExpectancy: 79.08,
    scientificTechnicalJournalArticles: 38,
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
  },
  {
    iso: "BD",
    country: "Bangladesh",
    year: 2018,
    gdpPerCap: 1203,
    population: 161.36,
    lifeExpectancy: 72.32,
    scientificTechnicalJournalArticles: 3135,
    patentApplications: 69,
    region: "Asia",
    subRegion: "Southern Asia",
  },
  {
    iso: "BE",
    country: "Belgium",
    year: 2018,
    gdpPerCap: 47036,
    population: 11.43,
    lifeExpectancy: 81.6,
    researchDevExpenditure: 2.82,
    scientificTechnicalJournalArticles: 15688,
    patentApplications: 892,
    region: "Europe",
    subRegion: "Western Europe",
  },
  {
    iso: "BF",
    country: "Burkina Faso",
    year: 2018,
    gdpPerCap: 800,
    population: 19.75,
    lifeExpectancy: 61.17,
    scientificTechnicalJournalArticles: 252,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
  {
    iso: "BG",
    country: "Bulgaria",
    year: 2018,
    gdpPerCap: 8675,
    population: 7.03,
    lifeExpectancy: 74.96,
    researchDevExpenditure: 0.77,
    scientificTechnicalJournalArticles: 3311,
    patentApplications: 180,
    region: "Europe",
    subRegion: "Eastern Europe",
  },
  {
    iso: "BH",
    country: "Bahrain",
    year: 2018,
    gdpPerCap: 21478,
    population: 1.57,
    lifeExpectancy: 77.16,
    scientificTechnicalJournalArticles: 322,
    patentApplications: 11,
    region: "Asia",
    subRegion: "Western Asia",
  },
  {
    iso: "BI",
    country: "Burundi",
    year: 2018,
    gdpPerCap: 211,
    population: 11.18,
    lifeExpectancy: 61.25,
    researchDevExpenditure: 0.21,
    scientificTechnicalJournalArticles: 21,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
  {
    iso: "BJ",
    country: "Benin",
    year: 2018,
    gdpPerCap: 1211,
    population: 11.49,
    lifeExpectancy: 61.47,
    scientificTechnicalJournalArticles: 228,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
  {
    iso: "BM",
    country: "Bermuda",
    year: 2018,
    gdpPerCap: 93832,
    population: 0.06,
    lifeExpectancy: 81.65,
    researchDevExpenditure: 0.26,
    region: "Americas",
    subRegion: "Northern America",
  },
  {
    iso: "BN",
    country: "Brunei Darussalam",
    year: 2018,
    gdpPerCap: 31437,
    population: 0.43,
    lifeExpectancy: 75.72,
    researchDevExpenditure: 0.28,
    scientificTechnicalJournalArticles: 294,
    patentApplications: 24,
    region: "Asia",
    subRegion: "South-eastern Asia",
  },
  {
    iso: "BO",
    country: "Bolivia",
    year: 2018,
    gdpPerCap: 2560,
    population: 11.35,
    lifeExpectancy: 71.24,
    scientificTechnicalJournalArticles: 103,
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
  },
  {
    iso: "BR",
    country: "Brazil",
    year: 2018,
    gdpPerCap: 11080,
    population: 209.47,
    lifeExpectancy: 75.67,
    scientificTechnicalJournalArticles: 60148,
    patentApplications: 4980,
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
  },
  {
    iso: "BS",
    country: "Bahamas, The",
    year: 2018,
    gdpPerCap: 28845,
    population: 0.39,
    lifeExpectancy: 73.75,
    scientificTechnicalJournalArticles: 20,
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
  },
  {
    iso: "BT",
    country: "Bhutan",
    year: 2018,
    gdpPerCap: 3129,
    population: 0.75,
    lifeExpectancy: 71.46,
    scientificTechnicalJournalArticles: 53,
    region: "Asia",
    subRegion: "Southern Asia",
  },
  {
    iso: "BW",
    country: "Botswana",
    year: 2018,
    gdpPerCap: 8033,
    population: 2.25,
    lifeExpectancy: 69.28,
    scientificTechnicalJournalArticles: 281,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
  {
    iso: "BY",
    country: "Belarus",
    year: 2018,
    gdpPerCap: 6586,
    population: 9.48,
    lifeExpectancy: 74.18,
    researchDevExpenditure: 0.61,
    scientificTechnicalJournalArticles: 1180,
    patentApplications: 453,
    region: "Europe",
    subRegion: "Eastern Europe",
  },
  {
    iso: "BZ",
    country: "Belize",
    year: 2018,
    gdpPerCap: 4217,
    population: 0.38,
    lifeExpectancy: 74.5,
    scientificTechnicalJournalArticles: 9,
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
  },
  {
    iso: "CA",
    country: "Canada",
    year: 2018,
    gdpPerCap: 51476,
    population: 37.06,
    lifeExpectancy: 81.95,
    researchDevExpenditure: 1.57,
    scientificTechnicalJournalArticles: 59968,
    patentApplications: 4349,
    region: "Americas",
    subRegion: "Northern America",
  },
  {
    iso: "CD",
    country: "Congo, Dem. Rep.",
    year: 2018,
    gdpPerCap: 419,
    population: 84.07,
    lifeExpectancy: 60.37,
    scientificTechnicalJournalArticles: 149,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
  {
    iso: "CF",
    country: "Central African Republic",
    year: 2018,
    gdpPerCap: 379,
    population: 4.67,
    lifeExpectancy: 52.8,
    scientificTechnicalJournalArticles: 20,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
  {
    iso: "CG",
    country: "Congo, Rep.",
    year: 2018,
    gdpPerCap: 2304,
    population: 5.24,
    lifeExpectancy: 64.29,
    scientificTechnicalJournalArticles: 67,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
  {
    iso: "CH",
    country: "Switzerland",
    year: 2018,
    gdpPerCap: 79235,
    population: 8.51,
    lifeExpectancy: 83.75,
    scientificTechnicalJournalArticles: 21379,
    patentApplications: 1283,
    region: "Europe",
    subRegion: "Western Europe",
  },
  {
    iso: "CI",
    country: "Cote d'Ivoire",
    year: 2018,
    gdpPerCap: 1668,
    population: 25.07,
    lifeExpectancy: 57.42,
    scientificTechnicalJournalArticles: 248,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
  {
    iso: "CL",
    country: "Chile",
    year: 2018,
    gdpPerCap: 15112,
    population: 18.73,
    lifeExpectancy: 80.04,
    scientificTechnicalJournalArticles: 7122,
    patentApplications: 406,
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
  },
  {
    iso: "CM",
    country: "Cameroon",
    year: 2018,
    gdpPerCap: 1502,
    population: 25.22,
    lifeExpectancy: 58.92,
    scientificTechnicalJournalArticles: 876,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
  {
    iso: "CN",
    country: "China",
    year: 2018,
    gdpPerCap: 7807,
    population: 1392.73,
    lifeExpectancy: 76.7,
    researchDevExpenditure: 2.19,
    scientificTechnicalJournalArticles: 528263,
    patentApplications: 1393815,
    region: "Asia",
    subRegion: "Eastern Asia",
  },
  {
    iso: "CO",
    country: "Colombia",
    year: 2018,
    gdpPerCap: 7694,
    population: 49.66,
    lifeExpectancy: 77.11,
    researchDevExpenditure: 0.24,
    scientificTechnicalJournalArticles: 7195,
    patentApplications: 415,
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
  },
  {
    iso: "CR",
    country: "Costa Rica",
    year: 2018,
    gdpPerCap: 9937,
    population: 5,
    lifeExpectancy: 80.09,
    scientificTechnicalJournalArticles: 507,
    patentApplications: 7,
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
  },
  {
    iso: "CU",
    country: "Cuba",
    year: 2018,
    gdpPerCap: 6817,
    population: 11.34,
    lifeExpectancy: 78.73,
    scientificTechnicalJournalArticles: 969,
    patentApplications: 29,
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
  },
  {
    iso: "CV",
    country: "Cabo Verde",
    year: 2018,
    gdpPerCap: 3740,
    population: 0.54,
    lifeExpectancy: 72.78,
    scientificTechnicalJournalArticles: 9,
    patentApplications: 3,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
  {
    iso: "CY",
    country: "Cyprus",
    year: 2018,
    gdpPerCap: 31507,
    population: 1.19,
    lifeExpectancy: 80.83,
    researchDevExpenditure: 0.56,
    scientificTechnicalJournalArticles: 1245,
    patentApplications: 4,
    region: "Asia",
    subRegion: "Western Asia",
  },
  {
    iso: "CZ",
    country: "Czech Republic",
    year: 2018,
    gdpPerCap: 23801,
    population: 10.63,
    lifeExpectancy: 79.03,
    researchDevExpenditure: 1.93,
    scientificTechnicalJournalArticles: 15577,
    patentApplications: 678,
    region: "Europe",
    subRegion: "Eastern Europe",
  },
  {
    iso: "DE",
    country: "Germany",
    year: 2018,
    gdpPerCap: 47314,
    population: 82.91,
    lifeExpectancy: 80.89,
    researchDevExpenditure: 3.09,
    scientificTechnicalJournalArticles: 104396,
    patentApplications: 46617,
    region: "Europe",
    subRegion: "Western Europe",
  },
  {
    iso: "DK",
    country: "Denmark",
    year: 2018,
    gdpPerCap: 64272,
    population: 5.79,
    lifeExpectancy: 80.95,
    researchDevExpenditure: 3.06,
    scientificTechnicalJournalArticles: 13979,
    patentApplications: 1262,
    region: "Europe",
    subRegion: "Northern Europe",
  },
  {
    iso: "DO",
    country: "Dominican Republic",
    year: 2018,
    gdpPerCap: 7698,
    population: 10.63,
    lifeExpectancy: 73.89,
    scientificTechnicalJournalArticles: 49,
    patentApplications: 17,
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
  },
  {
    iso: "DZ",
    country: "Algeria",
    year: 2018,
    gdpPerCap: 4754,
    population: 42.23,
    lifeExpectancy: 76.69,
    scientificTechnicalJournalArticles: 5231,
    patentApplications: 152,
    region: "Africa",
    subRegion: "Northern Africa",
  },
  {
    iso: "EC",
    country: "Ecuador",
    year: 2018,
    gdpPerCap: 5181,
    population: 17.08,
    lifeExpectancy: 76.8,
    scientificTechnicalJournalArticles: 2142,
    patentApplications: 34,
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
  },
  {
    iso: "EE",
    country: "Estonia",
    year: 2018,
    gdpPerCap: 19933,
    population: 1.32,
    lifeExpectancy: 78.24,
    researchDevExpenditure: 1.43,
    scientificTechnicalJournalArticles: 1415,
    patentApplications: 24,
    region: "Europe",
    subRegion: "Northern Europe",
  },
  {
    iso: "EG",
    country: "Egypt, Arab Rep.",
    year: 2018,
    gdpPerCap: 2909,
    population: 98.42,
    lifeExpectancy: 71.83,
    researchDevExpenditure: 0.72,
    scientificTechnicalJournalArticles: 13327,
    patentApplications: 997,
    region: "Africa",
    subRegion: "Northern Africa",
  },
  {
    iso: "ES",
    country: "Spain",
    year: 2018,
    gdpPerCap: 32949,
    population: 46.8,
    lifeExpectancy: 83.43,
    researchDevExpenditure: 1.24,
    scientificTechnicalJournalArticles: 54537,
    patentApplications: 1525,
    region: "Europe",
    subRegion: "Southern Europe",
  },
  {
    iso: "ET",
    country: "Ethiopia",
    year: 2018,
    gdpPerCap: 571,
    population: 109.22,
    lifeExpectancy: 66.24,
    scientificTechnicalJournalArticles: 1994,
    patentApplications: 13,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
  {
    iso: "FI",
    country: "Finland",
    year: 2018,
    gdpPerCap: 48880,
    population: 5.52,
    lifeExpectancy: 81.73,
    researchDevExpenditure: 2.77,
    scientificTechnicalJournalArticles: 10599,
    patentApplications: 1387,
    region: "Europe",
    subRegion: "Northern Europe",
  },
  {
    iso: "FJ",
    country: "Fiji",
    year: 2018,
    gdpPerCap: 4795,
    population: 0.88,
    lifeExpectancy: 67.34,
    scientificTechnicalJournalArticles: 140,
    region: "Oceania",
    subRegion: "Melanesia",
  },
  {
    iso: "FM",
    country: "Micronesia, Fed. Sts.",
    year: 2018,
    gdpPerCap: 2729,
    population: 0.11,
    lifeExpectancy: 67.75,
    scientificTechnicalJournalArticles: 4,
    region: "Oceania",
    subRegion: "Micronesia",
  },
  {
    iso: "FR",
    country: "France",
    year: 2018,
    gdpPerCap: 43720,
    population: 66.97,
    lifeExpectancy: 82.72,
    researchDevExpenditure: 2.2,
    scientificTechnicalJournalArticles: 66352,
    patentApplications: 14303,
    region: "Europe",
    subRegion: "Western Europe",
  },
  {
    iso: "GA",
    country: "Gabon",
    year: 2018,
    gdpPerCap: 9051,
    population: 2.12,
    lifeExpectancy: 66.19,
    scientificTechnicalJournalArticles: 64,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
  {
    iso: "GB",
    country: "United Kingdom",
    year: 2018,
    gdpPerCap: 43324,
    population: 66.46,
    lifeExpectancy: 81.26,
    researchDevExpenditure: 1.72,
    scientificTechnicalJournalArticles: 97681,
    patentApplications: 12865,
    region: "Europe",
    subRegion: "Northern Europe",
  },
  {
    iso: "GD",
    country: "Grenada",
    year: 2018,
    gdpPerCap: 9092,
    population: 0.11,
    lifeExpectancy: 72.38,
    scientificTechnicalJournalArticles: 46,
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
  },
  {
    iso: "GE",
    country: "Georgia",
    year: 2018,
    gdpPerCap: 4734,
    population: 3.73,
    lifeExpectancy: 73.6,
    researchDevExpenditure: 0.3,
    scientificTechnicalJournalArticles: 550,
    patentApplications: 103,
    region: "Asia",
    subRegion: "Western Asia",
  },
  {
    iso: "GH",
    country: "Ghana",
    year: 2018,
    gdpPerCap: 1808,
    population: 29.77,
    lifeExpectancy: 63.78,
    scientificTechnicalJournalArticles: 1276,
    patentApplications: 13,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
  {
    iso: "GM",
    country: "Gambia, The",
    year: 2018,
    gdpPerCap: 791,
    population: 2.28,
    lifeExpectancy: 61.73,
    researchDevExpenditure: 0.07,
    scientificTechnicalJournalArticles: 34,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
  {
    iso: "GN",
    country: "Guinea",
    year: 2018,
    gdpPerCap: 897,
    population: 12.41,
    lifeExpectancy: 61.19,
    scientificTechnicalJournalArticles: 28,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
  {
    iso: "GQ",
    country: "Equatorial Guinea",
    year: 2018,
    gdpPerCap: 10135,
    population: 1.31,
    lifeExpectancy: 58.4,
    scientificTechnicalJournalArticles: 3,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
  {
    iso: "GR",
    country: "Greece",
    year: 2018,
    gdpPerCap: 23547,
    population: 10.73,
    lifeExpectancy: 81.79,
    researchDevExpenditure: 1.18,
    scientificTechnicalJournalArticles: 10907,
    patentApplications: 430,
    region: "Europe",
    subRegion: "Southern Europe",
  },
  {
    iso: "GT",
    country: "Guatemala",
    year: 2018,
    gdpPerCap: 3339,
    population: 16.35,
    lifeExpectancy: 74.06,
    scientificTechnicalJournalArticles: 100,
    patentApplications: 6,
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
  },
  {
    iso: "GU",
    country: "Guam",
    year: 2018,
    gdpPerCap: 31477,
    population: 0.17,
    lifeExpectancy: 79.86,
    region: "Oceania",
    subRegion: "Micronesia",
  },
  {
    iso: "GW",
    country: "Guinea-Bissau",
    year: 2018,
    gdpPerCap: 623,
    population: 1.87,
    lifeExpectancy: 58,
    scientificTechnicalJournalArticles: 15,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
  {
    iso: "GY",
    country: "Guyana",
    year: 2018,
    gdpPerCap: 5825,
    population: 0.78,
    lifeExpectancy: 69.77,
    scientificTechnicalJournalArticles: 14,
    patentApplications: 2,
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
  },
  {
    iso: "HK",
    country: "Hong Kong SAR, China",
    year: 2018,
    gdpPerCap: 38699,
    population: 7.45,
    lifeExpectancy: 84.93,
    researchDevExpenditure: 0.86,
    patentApplications: 314,
    region: "Asia",
    subRegion: "Eastern Asia",
  },
  {
    iso: "HN",
    country: "Honduras",
    year: 2018,
    gdpPerCap: 2219,
    population: 9.59,
    lifeExpectancy: 75.09,
    scientificTechnicalJournalArticles: 45,
    patentApplications: 8,
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
  },
  {
    iso: "HR",
    country: "Croatia",
    year: 2018,
    gdpPerCap: 15971,
    population: 4.09,
    lifeExpectancy: 78.07,
    researchDevExpenditure: 0.97,
    scientificTechnicalJournalArticles: 4277,
    patentApplications: 121,
    region: "Europe",
    subRegion: "Southern Europe",
  },
  {
    iso: "HT",
    country: "Haiti",
    year: 2018,
    gdpPerCap: 1282,
    population: 11.12,
    lifeExpectancy: 63.66,
    scientificTechnicalJournalArticles: 29,
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
  },
  {
    iso: "HU",
    country: "Hungary",
    year: 2018,
    gdpPerCap: 16793,
    population: 9.78,
    lifeExpectancy: 76.07,
    researchDevExpenditure: 1.55,
    scientificTechnicalJournalArticles: 6701,
    patentApplications: 407,
    region: "Europe",
    subRegion: "Eastern Europe",
  },
  {
    iso: "ID",
    country: "Indonesia",
    year: 2018,
    gdpPerCap: 4285,
    population: 267.66,
    lifeExpectancy: 71.51,
    researchDevExpenditure: 0.23,
    scientificTechnicalJournalArticles: 26948,
    patentApplications: 1407,
    region: "Asia",
    subRegion: "South-eastern Asia",
  },
  {
    iso: "IE",
    country: "Ireland",
    year: 2018,
    gdpPerCap: 76663,
    population: 4.87,
    lifeExpectancy: 82.26,
    researchDevExpenditure: 1.15,
    scientificTechnicalJournalArticles: 7174,
    patentApplications: 76,
    region: "Europe",
    subRegion: "Northern Europe",
  },
  {
    iso: "IL",
    country: "Israel",
    year: 2018,
    gdpPerCap: 34750,
    population: 8.88,
    lifeExpectancy: 82.8,
    researchDevExpenditure: 4.95,
    scientificTechnicalJournalArticles: 12235,
    patentApplications: 1506,
    region: "Asia",
    subRegion: "Western Asia",
  },
  {
    iso: "IN",
    country: "India",
    year: 2018,
    gdpPerCap: 2086,
    population: 1352.62,
    lifeExpectancy: 69.42,
    researchDevExpenditure: 0.65,
    scientificTechnicalJournalArticles: 135788,
    patentApplications: 16289,
    region: "Asia",
    subRegion: "Southern Asia",
  },
  {
    iso: "IQ",
    country: "Iraq",
    year: 2018,
    gdpPerCap: 5475,
    population: 38.43,
    lifeExpectancy: 70.45,
    researchDevExpenditure: 0.04,
    scientificTechnicalJournalArticles: 6073,
    patentApplications: 653,
    region: "Asia",
    subRegion: "Western Asia",
  },
  {
    iso: "IR",
    country: "Iran, Islamic Rep.",
    year: 2018,
    gdpPerCap: 6440,
    population: 81.8,
    lifeExpectancy: 76.48,
    scientificTechnicalJournalArticles: 48306,
    patentApplications: 11908,
    region: "Asia",
    subRegion: "Southern Asia",
  },
  {
    iso: "IS",
    country: "Iceland",
    year: 2018,
    gdpPerCap: 51593,
    population: 0.35,
    lifeExpectancy: 82.86,
    researchDevExpenditure: 2.03,
    scientificTechnicalJournalArticles: 681,
    patentApplications: 56,
    region: "Europe",
    subRegion: "Northern Europe",
  },
  {
    iso: "IT",
    country: "Italy",
    year: 2018,
    gdpPerCap: 35485,
    population: 60.42,
    lifeExpectancy: 83.35,
    researchDevExpenditure: 1.4,
    scientificTechnicalJournalArticles: 71240,
    patentApplications: 8921,
    region: "Europe",
    subRegion: "Southern Europe",
  },
  {
    iso: "JM",
    country: "Jamaica",
    year: 2018,
    gdpPerCap: 4855,
    population: 2.93,
    lifeExpectancy: 74.37,
    scientificTechnicalJournalArticles: 164,
    patentApplications: 26,
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
  },
  {
    iso: "JO",
    country: "Jordan",
    year: 2018,
    gdpPerCap: 3310,
    population: 9.96,
    lifeExpectancy: 74.41,
    scientificTechnicalJournalArticles: 2627,
    patentApplications: 24,
    region: "Asia",
    subRegion: "Western Asia",
  },
  {
    iso: "JP",
    country: "Japan",
    year: 2018,
    gdpPerCap: 48766,
    population: 126.53,
    lifeExpectancy: 84.21,
    researchDevExpenditure: 3.26,
    scientificTechnicalJournalArticles: 98792,
    patentApplications: 253630,
    region: "Asia",
    subRegion: "Eastern Asia",
  },
  {
    iso: "KE",
    country: "Kenya",
    year: 2018,
    gdpPerCap: 1201,
    population: 51.39,
    lifeExpectancy: 66.34,
    scientificTechnicalJournalArticles: 1247,
    patentApplications: 244,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
  {
    iso: "KG",
    country: "Kyrgyz Republic",
    year: 2018,
    gdpPerCap: 1091,
    population: 6.32,
    lifeExpectancy: 71.4,
    scientificTechnicalJournalArticles: 137,
    region: "Asia",
    subRegion: "Central Asia",
  },
  {
    iso: "KH",
    country: "Cambodia",
    year: 2018,
    gdpPerCap: 1203,
    population: 16.25,
    lifeExpectancy: 69.57,
    scientificTechnicalJournalArticles: 146,
    region: "Asia",
    subRegion: "South-eastern Asia",
  },
  {
    iso: "KI",
    country: "Kiribati",
    year: 2018,
    gdpPerCap: 1778,
    population: 0.12,
    lifeExpectancy: 68.12,
    scientificTechnicalJournalArticles: 1,
    region: "Oceania",
    subRegion: "Micronesia",
  },
  {
    iso: "KM",
    country: "Comoros",
    year: 2018,
    gdpPerCap: 1403,
    population: 0.83,
    lifeExpectancy: 64.12,
    scientificTechnicalJournalArticles: 3,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
  {
    iso: "KR",
    country: "Korea, Rep.",
    year: 2018,
    gdpPerCap: 28158,
    population: 51.61,
    lifeExpectancy: 82.63,
    researchDevExpenditure: 4.81,
    scientificTechnicalJournalArticles: 66376,
    patentApplications: 162561,
    region: "Asia",
    subRegion: "Eastern Asia",
  },
  {
    iso: "KW",
    country: "Kuwait",
    year: 2018,
    gdpPerCap: 33112,
    population: 4.14,
    lifeExpectancy: 75.4,
    researchDevExpenditure: 0.06,
    scientificTechnicalJournalArticles: 1004,
    patentApplications: 1,
    region: "Asia",
    subRegion: "Western Asia",
  },
  {
    iso: "KZ",
    country: "Kazakhstan",
    year: 2018,
    gdpPerCap: 11166,
    population: 18.28,
    lifeExpectancy: 73.15,
    researchDevExpenditure: 0.12,
    scientificTechnicalJournalArticles: 2367,
    patentApplications: 789,
    region: "Asia",
    subRegion: "Central Asia",
  },
  {
    iso: "LA",
    country: "Lao PDR",
    year: 2018,
    gdpPerCap: 1786,
    population: 7.06,
    lifeExpectancy: 67.61,
    scientificTechnicalJournalArticles: 87,
    patentApplications: 1,
    region: "Asia",
    subRegion: "South-eastern Asia",
  },
  {
    iso: "LB",
    country: "Lebanon",
    year: 2018,
    gdpPerCap: 6214,
    population: 6.85,
    lifeExpectancy: 78.88,
    scientificTechnicalJournalArticles: 1776,
    region: "Asia",
    subRegion: "Western Asia",
  },
  {
    iso: "LC",
    country: "St. Lucia",
    year: 2018,
    gdpPerCap: 9237,
    population: 0.18,
    lifeExpectancy: 76.06,
    scientificTechnicalJournalArticles: 4,
    patentApplications: 2,
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
  },
  {
    iso: "LK",
    country: "Sri Lanka",
    year: 2018,
    gdpPerCap: 3946,
    population: 21.67,
    lifeExpectancy: 76.81,
    scientificTechnicalJournalArticles: 1348,
    patentApplications: 343,
    region: "Asia",
    subRegion: "Southern Asia",
  },
  {
    iso: "LR",
    country: "Liberia",
    year: 2018,
    gdpPerCap: 541,
    population: 4.82,
    lifeExpectancy: 63.73,
    scientificTechnicalJournalArticles: 25,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
  {
    iso: "LS",
    country: "Lesotho",
    year: 2018,
    gdpPerCap: 1375,
    population: 2.11,
    lifeExpectancy: 53.7,
    scientificTechnicalJournalArticles: 19,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
  {
    iso: "LT",
    country: "Lithuania",
    year: 2018,
    gdpPerCap: 17742,
    population: 2.8,
    lifeExpectancy: 75.68,
    researchDevExpenditure: 0.94,
    scientificTechnicalJournalArticles: 2267,
    patentApplications: 81,
    region: "Europe",
    subRegion: "Northern Europe",
  },
  {
    iso: "LU",
    country: "Luxembourg",
    year: 2018,
    gdpPerCap: 110702,
    population: 0.61,
    lifeExpectancy: 82.3,
    researchDevExpenditure: 1.24,
    scientificTechnicalJournalArticles: 869,
    patentApplications: 152,
    region: "Europe",
    subRegion: "Western Europe",
  },
  {
    iso: "LV",
    country: "Latvia",
    year: 2018,
    gdpPerCap: 16263,
    population: 1.93,
    lifeExpectancy: 74.78,
    researchDevExpenditure: 0.63,
    scientificTechnicalJournalArticles: 1418,
    patentApplications: 86,
    region: "Europe",
    subRegion: "Northern Europe",
  },
  {
    iso: "LY",
    country: "Libya",
    year: 2018,
    gdpPerCap: 8039,
    population: 6.68,
    lifeExpectancy: 72.72,
    scientificTechnicalJournalArticles: 162,
    region: "Africa",
    subRegion: "Northern Africa",
  },
  {
    iso: "MA",
    country: "Morocco",
    year: 2018,
    gdpPerCap: 3361,
    population: 36.03,
    lifeExpectancy: 76.45,
    scientificTechnicalJournalArticles: 5057,
    patentApplications: 187,
    region: "Africa",
    subRegion: "Northern Africa",
  },
  {
    iso: "MD",
    country: "Moldova",
    year: 2018,
    gdpPerCap: 3527,
    population: 2.71,
    lifeExpectancy: 71.81,
    researchDevExpenditure: 0.25,
    scientificTechnicalJournalArticles: 210,
    patentApplications: 92,
    region: "Europe",
    subRegion: "Eastern Europe",
  },
  {
    iso: "ME",
    country: "Montenegro",
    year: 2018,
    gdpPerCap: 8253,
    population: 0.62,
    lifeExpectancy: 76.77,
    researchDevExpenditure: 0.37,
    scientificTechnicalJournalArticles: 250,
    patentApplications: 3,
    region: "Europe",
    subRegion: "Southern Europe",
  },
  {
    iso: "MG",
    country: "Madagascar",
    year: 2018,
    gdpPerCap: 490,
    population: 26.26,
    lifeExpectancy: 66.68,
    scientificTechnicalJournalArticles: 127,
    patentApplications: 9,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
  {
    iso: "MK",
    country: "North Macedonia",
    year: 2018,
    gdpPerCap: 5452,
    population: 2.08,
    lifeExpectancy: 75.69,
    researchDevExpenditure: 0.36,
    scientificTechnicalJournalArticles: 493,
    region: "Europe",
    subRegion: "Southern Europe",
  },
  {
    iso: "ML",
    country: "Mali",
    year: 2018,
    gdpPerCap: 779,
    population: 19.08,
    lifeExpectancy: 58.89,
    scientificTechnicalJournalArticles: 90,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
  {
    iso: "MM",
    country: "Myanmar",
    year: 2018,
    gdpPerCap: 1573,
    population: 53.71,
    lifeExpectancy: 66.87,
    scientificTechnicalJournalArticles: 231,
    region: "Asia",
    subRegion: "South-eastern Asia",
  },
  {
    iso: "MN",
    country: "Mongolia",
    year: 2018,
    gdpPerCap: 4211,
    population: 3.17,
    lifeExpectancy: 69.69,
    researchDevExpenditure: 0.1,
    scientificTechnicalJournalArticles: 141,
    patentApplications: 82,
    region: "Asia",
    subRegion: "Eastern Asia",
  },
  {
    iso: "MO",
    country: "Macao SAR, China",
    year: 2018,
    gdpPerCap: 58642,
    population: 0.63,
    lifeExpectancy: 84.12,
    researchDevExpenditure: 0.2,
    patentApplications: 1,
    region: "Asia",
    subRegion: "Eastern Asia",
  },
  {
    iso: "MR",
    country: "Mauritania",
    year: 2018,
    gdpPerCap: 1704,
    population: 4.4,
    lifeExpectancy: 64.7,
    researchDevExpenditure: 0.01,
    scientificTechnicalJournalArticles: 20,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
  {
    iso: "MT",
    country: "Malta",
    year: 2018,
    gdpPerCap: 28644,
    population: 0.48,
    lifeExpectancy: 82.45,
    researchDevExpenditure: 0.57,
    scientificTechnicalJournalArticles: 422,
    region: "Europe",
    subRegion: "Southern Europe",
  },
  {
    iso: "MU",
    country: "Mauritius",
    year: 2018,
    gdpPerCap: 10577,
    population: 1.27,
    lifeExpectancy: 74.42,
    researchDevExpenditure: 0.35,
    scientificTechnicalJournalArticles: 127,
    patentApplications: 16,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
  {
    iso: "MV",
    country: "Maldives",
    year: 2018,
    gdpPerCap: 8157,
    population: 0.52,
    lifeExpectancy: 78.63,
    scientificTechnicalJournalArticles: 7,
    region: "Asia",
    subRegion: "Southern Asia",
  },
  {
    iso: "MW",
    country: "Malawi",
    year: 2018,
    gdpPerCap: 515,
    population: 18.14,
    lifeExpectancy: 63.8,
    scientificTechnicalJournalArticles: 231,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
  {
    iso: "MX",
    country: "Mexico",
    year: 2018,
    gdpPerCap: 10386,
    population: 126.19,
    lifeExpectancy: 74.99,
    researchDevExpenditure: 0.31,
    scientificTechnicalJournalArticles: 16346,
    patentApplications: 1555,
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
  },
  {
    iso: "MY",
    country: "Malaysia",
    year: 2018,
    gdpPerCap: 12131,
    population: 31.53,
    lifeExpectancy: 76,
    scientificTechnicalJournalArticles: 23661,
    patentApplications: 1116,
    region: "Asia",
    subRegion: "South-eastern Asia",
  },
  {
    iso: "MZ",
    country: "Mozambique",
    year: 2018,
    gdpPerCap: 593,
    population: 29.5,
    lifeExpectancy: 60.16,
    scientificTechnicalJournalArticles: 139,
    patentApplications: 34,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
  {
    iso: "NE",
    country: "Niger",
    year: 2018,
    gdpPerCap: 552,
    population: 22.44,
    lifeExpectancy: 62.02,
    scientificTechnicalJournalArticles: 55,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
  {
    iso: "NG",
    country: "Nigeria",
    year: 2018,
    gdpPerCap: 2383,
    population: 195.87,
    lifeExpectancy: 54.33,
    scientificTechnicalJournalArticles: 5602,
    patentApplications: 120,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
  {
    iso: "NI",
    country: "Nicaragua",
    year: 2018,
    gdpPerCap: 1857,
    population: 6.47,
    lifeExpectancy: 74.28,
    scientificTechnicalJournalArticles: 44,
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
  },
  {
    iso: "NL",
    country: "Netherlands",
    year: 2018,
    gdpPerCap: 54894,
    population: 17.23,
    lifeExpectancy: 81.81,
    researchDevExpenditure: 2.16,
    scientificTechnicalJournalArticles: 30457,
    patentApplications: 2111,
    region: "Europe",
    subRegion: "Western Europe",
  },
  {
    iso: "NO",
    country: "Norway",
    year: 2018,
    gdpPerCap: 92120,
    population: 5.31,
    lifeExpectancy: 82.76,
    researchDevExpenditure: 2.07,
    scientificTechnicalJournalArticles: 11803,
    patentApplications: 1082,
    region: "Europe",
    subRegion: "Northern Europe",
  },
  {
    iso: "NP",
    country: "Nepal",
    year: 2018,
    gdpPerCap: 818,
    population: 28.09,
    lifeExpectancy: 70.48,
    scientificTechnicalJournalArticles: 792,
    region: "Asia",
    subRegion: "Southern Asia",
  },
  {
    iso: "NZ",
    country: "New Zealand",
    year: 2018,
    gdpPerCap: 38522,
    population: 4.84,
    lifeExpectancy: 81.86,
    scientificTechnicalJournalArticles: 7889,
    patentApplications: 1017,
    region: "Oceania",
    subRegion: "Australia and New Zealand",
  },
  {
    iso: "OM",
    country: "Oman",
    year: 2018,
    gdpPerCap: 15797,
    population: 4.83,
    lifeExpectancy: 77.63,
    researchDevExpenditure: 0.22,
    scientificTechnicalJournalArticles: 856,
    region: "Asia",
    subRegion: "Western Asia",
  },
  {
    iso: "PA",
    country: "Panama",
    year: 2018,
    gdpPerCap: 11755,
    population: 4.18,
    lifeExpectancy: 78.33,
    scientificTechnicalJournalArticles: 173,
    patentApplications: 135,
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
  },
  {
    iso: "PE",
    country: "Peru",
    year: 2018,
    gdpPerCap: 6454,
    population: 31.99,
    lifeExpectancy: 76.52,
    researchDevExpenditure: 0.13,
    scientificTechnicalJournalArticles: 1630,
    patentApplications: 89,
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
  },
  {
    iso: "PG",
    country: "Papua New Guinea",
    year: 2018,
    gdpPerCap: 2398,
    population: 8.61,
    lifeExpectancy: 64.26,
    scientificTechnicalJournalArticles: 64,
    region: "Oceania",
    subRegion: "Melanesia",
  },
  {
    iso: "PH",
    country: "Philippines",
    year: 2018,
    gdpPerCap: 3191,
    population: 106.65,
    lifeExpectancy: 71.09,
    scientificTechnicalJournalArticles: 2237,
    patentApplications: 529,
    region: "Asia",
    subRegion: "South-eastern Asia",
  },
  {
    iso: "PK",
    country: "Pakistan",
    year: 2018,
    gdpPerCap: 1198,
    population: 212.22,
    lifeExpectancy: 67.11,
    scientificTechnicalJournalArticles: 12904,
    patentApplications: 306,
    region: "Asia",
    subRegion: "Southern Asia",
  },
  {
    iso: "PL",
    country: "Poland",
    year: 2018,
    gdpPerCap: 16649,
    population: 37.97,
    lifeExpectancy: 77.6,
    researchDevExpenditure: 1.21,
    scientificTechnicalJournalArticles: 35663,
    patentApplications: 4207,
    region: "Europe",
    subRegion: "Eastern Europe",
  },
  {
    iso: "PR",
    country: "Puerto Rico",
    year: 2018,
    gdpPerCap: 27362,
    population: 3.19,
    lifeExpectancy: 79.78,
    scientificTechnicalJournalArticles: 515,
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
  },
  {
    iso: "PS",
    country: "West Bank and Gaza",
    year: 2018,
    gdpPerCap: 2986,
    population: 4.57,
    lifeExpectancy: 73.89,
    scientificTechnicalJournalArticles: 376,
    region: "Asia",
    subRegion: "Western Asia",
  },
  {
    iso: "PT",
    country: "Portugal",
    year: 2018,
    gdpPerCap: 24085,
    population: 10.28,
    lifeExpectancy: 81.32,
    researchDevExpenditure: 1.37,
    scientificTechnicalJournalArticles: 14295,
    patentApplications: 661,
    region: "Europe",
    subRegion: "Southern Europe",
  },
  {
    iso: "PY",
    country: "Paraguay",
    year: 2018,
    gdpPerCap: 5380,
    population: 6.96,
    lifeExpectancy: 74.13,
    scientificTechnicalJournalArticles: 98,
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
  },
  {
    iso: "QA",
    country: "Qatar",
    year: 2018,
    gdpPerCap: 63933,
    population: 2.78,
    lifeExpectancy: 80.1,
    researchDevExpenditure: 0.51,
    scientificTechnicalJournalArticles: 1503,
    region: "Asia",
    subRegion: "Western Asia",
  },
  {
    iso: "RO",
    country: "Romania",
    year: 2018,
    gdpPerCap: 11541,
    population: 19.47,
    lifeExpectancy: 75.36,
    researchDevExpenditure: 0.51,
    scientificTechnicalJournalArticles: 10345,
    patentApplications: 1100,
    region: "Europe",
    subRegion: "Eastern Europe",
  },
  {
    iso: "RS",
    country: "Serbia",
    year: 2018,
    gdpPerCap: 6898,
    population: 6.98,
    lifeExpectancy: 75.89,
    researchDevExpenditure: 0.92,
    scientificTechnicalJournalArticles: 4523,
    patentApplications: 163,
    region: "Europe",
    subRegion: "Southern Europe",
  },
  {
    iso: "RU",
    country: "Russian Federation",
    year: 2018,
    gdpPerCap: 11844,
    population: 144.48,
    lifeExpectancy: 72.66,
    researchDevExpenditure: 0.99,
    scientificTechnicalJournalArticles: 81579,
    patentApplications: 24926,
    region: "Europe",
    subRegion: "Eastern Europe",
  },
  {
    iso: "RW",
    country: "Rwanda",
    year: 2018,
    gdpPerCap: 845,
    population: 12.3,
    lifeExpectancy: 68.7,
    scientificTechnicalJournalArticles: 170,
    patentApplications: 6,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
  {
    iso: "SA",
    country: "Saudi Arabia",
    year: 2018,
    gdpPerCap: 20820,
    population: 33.7,
    lifeExpectancy: 75,
    scientificTechnicalJournalArticles: 10898,
    patentApplications: 1078,
    region: "Asia",
    subRegion: "Western Asia",
  },
  {
    iso: "SB",
    country: "Solomon Islands",
    year: 2018,
    gdpPerCap: 1774,
    population: 0.65,
    lifeExpectancy: 72.83,
    scientificTechnicalJournalArticles: 13,
    region: "Oceania",
    subRegion: "Melanesia",
  },
  {
    iso: "SC",
    country: "Seychelles",
    year: 2018,
    gdpPerCap: 14417,
    population: 0.1,
    lifeExpectancy: 72.84,
    scientificTechnicalJournalArticles: 10,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
  {
    iso: "SD",
    country: "Sudan",
    year: 2018,
    gdpPerCap: 1812,
    population: 41.8,
    lifeExpectancy: 65.09,
    scientificTechnicalJournalArticles: 398,
    patentApplications: 349,
    region: "Africa",
    subRegion: "Northern Africa",
  },
  {
    iso: "SE",
    country: "Sweden",
    year: 2018,
    gdpPerCap: 57911,
    population: 10.18,
    lifeExpectancy: 82.56,
    researchDevExpenditure: 3.34,
    scientificTechnicalJournalArticles: 20421,
    patentApplications: 1838,
    region: "Europe",
    subRegion: "Northern Europe",
  },
  {
    iso: "SG",
    country: "Singapore",
    year: 2018,
    gdpPerCap: 59073,
    population: 5.64,
    lifeExpectancy: 83.15,
    scientificTechnicalJournalArticles: 11459,
    patentApplications: 1575,
    region: "Asia",
    subRegion: "South-eastern Asia",
  },
  {
    iso: "SI",
    country: "Slovenia",
    year: 2018,
    gdpPerCap: 26760,
    population: 2.07,
    lifeExpectancy: 81.38,
    researchDevExpenditure: 1.94,
    scientificTechnicalJournalArticles: 3206,
    patentApplications: 255,
    region: "Europe",
    subRegion: "Southern Europe",
  },
  {
    iso: "SK",
    country: "Slovak Republic",
    year: 2018,
    gdpPerCap: 20551,
    population: 5.45,
    lifeExpectancy: 77.27,
    researchDevExpenditure: 0.83,
    scientificTechnicalJournalArticles: 5322,
    patentApplications: 217,
    region: "Europe",
    subRegion: "Eastern Europe",
  },
  {
    iso: "SL",
    country: "Sierra Leone",
    year: 2018,
    gdpPerCap: 473,
    population: 7.65,
    lifeExpectancy: 54.31,
    scientificTechnicalJournalArticles: 41,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
  {
    iso: "SN",
    country: "Senegal",
    year: 2018,
    gdpPerCap: 1547,
    population: 15.85,
    lifeExpectancy: 67.67,
    scientificTechnicalJournalArticles: 388,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
  {
    iso: "SR",
    country: "Suriname",
    year: 2018,
    gdpPerCap: 8100,
    population: 0.58,
    lifeExpectancy: 71.57,
    scientificTechnicalJournalArticles: 17,
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
  },
  {
    iso: "ST",
    country: "Sao Tome and Principe",
    year: 2018,
    gdpPerCap: 1297,
    population: 0.21,
    lifeExpectancy: 70.17,
    scientificTechnicalJournalArticles: 1,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
  {
    iso: "SV",
    country: "El Salvador",
    year: 2018,
    gdpPerCap: 3507,
    population: 6.42,
    lifeExpectancy: 73.1,
    scientificTechnicalJournalArticles: 45,
    patentApplications: 3,
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
  },
  {
    iso: "SZ",
    country: "Eswatini",
    year: 2018,
    gdpPerCap: 4762,
    population: 1.14,
    lifeExpectancy: 59.4,
    scientificTechnicalJournalArticles: 34,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
  {
    iso: "TD",
    country: "Chad",
    year: 2018,
    gdpPerCap: 812,
    population: 15.48,
    lifeExpectancy: 53.98,
    scientificTechnicalJournalArticles: 15,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
  {
    iso: "TG",
    country: "Togo",
    year: 2018,
    gdpPerCap: 677,
    population: 7.89,
    lifeExpectancy: 60.76,
    scientificTechnicalJournalArticles: 86,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
  {
    iso: "TH",
    country: "Thailand",
    year: 2018,
    gdpPerCap: 6370,
    population: 69.43,
    lifeExpectancy: 76.93,
    scientificTechnicalJournalArticles: 12514,
    patentApplications: 904,
    region: "Asia",
    subRegion: "South-eastern Asia",
  },
  {
    iso: "TJ",
    country: "Tajikistan",
    year: 2018,
    gdpPerCap: 1073,
    population: 9.1,
    lifeExpectancy: 70.88,
    researchDevExpenditure: 0.1,
    scientificTechnicalJournalArticles: 62,
    region: "Asia",
    subRegion: "Central Asia",
  },
  {
    iso: "TL",
    country: "Timor-Leste",
    year: 2018,
    gdpPerCap: 840,
    population: 1.27,
    lifeExpectancy: 69.26,
    scientificTechnicalJournalArticles: 14,
    region: "Asia",
    subRegion: "South-eastern Asia",
  },
  {
    iso: "TM",
    country: "Turkmenistan",
    year: 2018,
    gdpPerCap: 7648,
    population: 5.85,
    lifeExpectancy: 68.07,
    scientificTechnicalJournalArticles: 4,
    region: "Asia",
    subRegion: "Central Asia",
  },
  {
    iso: "TN",
    country: "Tunisia",
    year: 2018,
    gdpPerCap: 4408,
    population: 11.57,
    lifeExpectancy: 76.5,
    researchDevExpenditure: 0.6,
    scientificTechnicalJournalArticles: 5565,
    patentApplications: 180,
    region: "Africa",
    subRegion: "Northern Africa",
  },
  {
    iso: "TO",
    country: "Tonga",
    year: 2018,
    gdpPerCap: 4378,
    population: 0.1,
    lifeExpectancy: 70.8,
    scientificTechnicalJournalArticles: 5,
    region: "Oceania",
    subRegion: "Polynesia",
  },
  {
    iso: "TR",
    country: "Turkey",
    year: 2018,
    gdpPerCap: 15190,
    population: 82.32,
    lifeExpectancy: 77.44,
    scientificTechnicalJournalArticles: 33536,
    patentApplications: 7156,
    region: "Asia",
    subRegion: "Western Asia",
  },
  {
    iso: "TT",
    country: "Trinidad and Tobago",
    year: 2018,
    gdpPerCap: 15161,
    population: 1.39,
    lifeExpectancy: 73.38,
    scientificTechnicalJournalArticles: 211,
    patentApplications: 4,
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
  },
  {
    iso: "TZ",
    country: "Tanzania",
    year: 2018,
    gdpPerCap: 959,
    population: 56.32,
    lifeExpectancy: 65.02,
    scientificTechnicalJournalArticles: 603,
    patentApplications: 25,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
  {
    iso: "UA",
    country: "Ukraine",
    year: 2018,
    gdpPerCap: 3106,
    population: 44.62,
    lifeExpectancy: 71.58,
    researchDevExpenditure: 0.47,
    scientificTechnicalJournalArticles: 10380,
    patentApplications: 2107,
    region: "Europe",
    subRegion: "Eastern Europe",
  },
  {
    iso: "UG",
    country: "Uganda",
    year: 2018,
    gdpPerCap: 934,
    population: 42.72,
    lifeExpectancy: 62.97,
    scientificTechnicalJournalArticles: 673,
    patentApplications: 6,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
  {
    iso: "US",
    country: "United States",
    year: 2018,
    gdpPerCap: 54833,
    population: 326.69,
    lifeExpectancy: 78.54,
    researchDevExpenditure: 2.84,
    scientificTechnicalJournalArticles: 422808,
    patentApplications: 285095,
    region: "Americas",
    subRegion: "Northern America",
  },
  {
    iso: "UY",
    country: "Uruguay",
    year: 2018,
    gdpPerCap: 14617,
    population: 3.45,
    lifeExpectancy: 77.77,
    scientificTechnicalJournalArticles: 852,
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
  },
  {
    iso: "UZ",
    country: "Uzbekistan",
    year: 2018,
    gdpPerCap: 2374,
    population: 32.96,
    lifeExpectancy: 71.57,
    researchDevExpenditure: 0.13,
    scientificTechnicalJournalArticles: 354,
    patentApplications: 470,
    region: "Asia",
    subRegion: "Central Asia",
  },
  {
    iso: "VC",
    country: "St. Vincent and the Grenadines",
    year: 2018,
    gdpPerCap: 6853,
    population: 0.11,
    lifeExpectancy: 72.42,
    scientificTechnicalJournalArticles: 1,
    region: "Americas",
    subRegion: "Latin America and the Caribbean",
  },
  {
    iso: "VN",
    country: "Vietnam",
    year: 2018,
    gdpPerCap: 1964,
    population: 95.54,
    lifeExpectancy: 75.32,
    scientificTechnicalJournalArticles: 4286,
    patentApplications: 646,
    region: "Asia",
    subRegion: "South-eastern Asia",
  },
  {
    iso: "VU",
    country: "Vanuatu",
    year: 2018,
    gdpPerCap: 2865,
    population: 0.29,
    lifeExpectancy: 70.32,
    scientificTechnicalJournalArticles: 6,
    region: "Oceania",
    subRegion: "Melanesia",
  },
  {
    iso: "WS",
    country: "Samoa",
    year: 2018,
    gdpPerCap: 3754,
    population: 0.2,
    lifeExpectancy: 73.19,
    scientificTechnicalJournalArticles: 11,
    patentApplications: 1,
    region: "Oceania",
    subRegion: "Polynesia",
  },
  {
    iso: "YE",
    country: "Yemen, Rep.",
    year: 2018,
    gdpPerCap: 633,
    population: 28.5,
    lifeExpectancy: 66.1,
    scientificTechnicalJournalArticles: 137,
    region: "Asia",
    subRegion: "Western Asia",
  },
  {
    iso: "ZA",
    country: "South Africa",
    year: 2018,
    gdpPerCap: 7434,
    population: 57.78,
    lifeExpectancy: 63.86,
    scientificTechnicalJournalArticles: 13009,
    patentApplications: 657,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
  {
    iso: "ZM",
    country: "Zambia",
    year: 2018,
    gdpPerCap: 1678,
    population: 17.35,
    lifeExpectancy: 63.51,
    scientificTechnicalJournalArticles: 213,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
  {
    iso: "ZW",
    country: "Zimbabwe",
    year: 2018,
    gdpPerCap: 1306,
    population: 14.44,
    lifeExpectancy: 61.2,
    scientificTechnicalJournalArticles: 359,
    region: "Africa",
    subRegion: "Sub-Saharan Africa",
  },
];
